using System.Collections.Generic;

namespace Bot.GameData;

public static class TechTree {
    public static readonly Dictionary<uint, uint> Producer = new Dictionary<uint, uint>
    {
        { Units.Drone,                       Units.Larva },
        { Units.Corruptor,                   Units.Larva },
        { Units.BroodLord,                   Units.Corruptor },
        { Units.Hydralisk,                   Units.Larva },
        { Units.Lurker,                      Units.Hydralisk },
        { Units.Infestor,                    Units.Larva },
        { Units.Mutalisk,                    Units.Larva },
        { Units.Overlord,                    Units.Larva },
        { Units.Overseer,                    Units.Overlord },
        { Units.Queen,                       Units.Hatchery },
        { Units.Roach,                       Units.Larva },
        { Units.Ravager,                     Units.Roach },
        { Units.Ultralisk,                   Units.Larva },
        { Units.Zergling,                    Units.Larva },
        { Units.SwarmHost,                   Units.Larva },
        { Units.Viper,                       Units.Larva },
        { Units.Baneling,                    Units.Zergling },
        { Units.BanelingNest,                Units.Drone },
        { Units.EvolutionChamber,            Units.Drone },
        { Units.Extractor,                   Units.Drone },
        { Units.Hatchery,                    Units.Drone },
        { Units.Lair,                        Units.Hatchery },
        { Units.Hive,                        Units.Lair },
        { Units.HydraliskDen,                Units.Drone },
        { Units.LurkerDen,                   Units.HydraliskDen },
        { Units.InfestationPit,              Units.Drone },
        { Units.NydusNetwork,                Units.Drone },
        { Units.RoachWarren,                 Units.Drone },
        { Units.SpawningPool,                Units.Drone },
        { Units.SpineCrawler,                Units.Drone },
        { Units.Spire,                       Units.Drone },
        { Units.GreaterSpire,                Units.Spire },
        { Units.SporeCrawler,                Units.Drone },
        { Units.UltraliskCavern,             Units.Drone },

        { Upgrades.ZergMissileWeaponsLevel1, Units.EvolutionChamber },
        { Upgrades.ZergMissileWeaponsLevel2, Units.EvolutionChamber },
        { Upgrades.ZergMissileWeaponsLevel3, Units.EvolutionChamber },
        { Upgrades.ZergMeleeWeaponsLevel1,   Units.EvolutionChamber },
        { Upgrades.ZergMeleeWeaponsLevel2,   Units.EvolutionChamber },
        { Upgrades.ZergMeleeWeaponsLevel3,   Units.EvolutionChamber },
        { Upgrades.ZergGroundArmorsLevel1,   Units.EvolutionChamber },
        { Upgrades.ZergGroundArmorsLevel2,   Units.EvolutionChamber },
        { Upgrades.ZergGroundArmorsLevel3,   Units.EvolutionChamber },
        { Upgrades.GlialReconstitution,      Units.RoachWarren },
        { Upgrades.TunnelingClaws,           Units.RoachWarren },
        { Upgrades.Burrow,                   Units.Hatchery },
    };

    public static readonly Dictionary<uint, uint> MorphSource = new Dictionary<uint, uint>
    {
        { Units.Drone,            Units.Larva },
        { Units.Corruptor,        Units.Larva },
        { Units.BroodLord,        Units.Corruptor },
        { Units.Hydralisk,        Units.Larva },
        { Units.Lurker,           Units.Hydralisk },
        { Units.Infestor,         Units.Larva },
        { Units.Mutalisk,         Units.Larva },
        { Units.Overlord,         Units.Larva },
        { Units.Overseer,         Units.Overlord },
        { Units.Roach,            Units.Larva },
        { Units.Ravager,          Units.Roach },
        { Units.Ultralisk,        Units.Larva },
        { Units.Zergling,         Units.Larva },
        { Units.SwarmHost,        Units.Larva },
        { Units.Viper,            Units.Larva },
        { Units.Baneling,         Units.Zergling },
        { Units.BanelingNest,     Units.Drone },
        { Units.EvolutionChamber, Units.Drone },
        { Units.Extractor,        Units.Drone },
        { Units.Hatchery,         Units.Drone },
        { Units.Lair,             Units.Hatchery },
        { Units.Hive,             Units.Lair },
        { Units.HydraliskDen,     Units.Drone },
        { Units.LurkerDen,        Units.Drone },
        { Units.InfestationPit,   Units.Drone },
        { Units.NydusNetwork,     Units.Drone },
        { Units.RoachWarren,      Units.Drone },
        { Units.SpawningPool,     Units.Drone },
        { Units.SpineCrawler,     Units.Drone },
        { Units.Spire,            Units.Drone },
        { Units.GreaterSpire,     Units.Spire },
        { Units.SporeCrawler,     Units.Drone },
        { Units.UltraliskCavern,  Units.Drone },
    };

    public static readonly Dictionary<uint, List<IPrerequisite>> UnitPrerequisites = new Dictionary<uint, List<IPrerequisite>>
    {
        { Units.EvolutionChamber,            new List<IPrerequisite> { new UnitPrerequisite(Units.Hatchery) }},
        { Units.SpawningPool,                new List<IPrerequisite> { new UnitPrerequisite(Units.Hatchery) }},
        { Units.Zergling,                    new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.Queen,                       new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.SpineCrawler,                new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.SporeCrawler,                new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.BanelingNest,                new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.Baneling,                    new List<IPrerequisite> { new UnitPrerequisite(Units.BanelingNest) }},
        { Units.RoachWarren,                 new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.Roach,                       new List<IPrerequisite> { new UnitPrerequisite(Units.RoachWarren) }},
        { Units.Ravager,                     new List<IPrerequisite> { new UnitPrerequisite(Units.RoachWarren) }},
        { Units.Lair,                        new List<IPrerequisite> { new UnitPrerequisite(Units.SpawningPool) }},
        { Units.Overseer,                    new List<IPrerequisite> { new UnitPrerequisite(Units.Lair) }},
        { Units.NydusNetwork,                new List<IPrerequisite> { new UnitPrerequisite(Units.Lair) }},
        { Units.NydusWorm,                   new List<IPrerequisite> { new UnitPrerequisite(Units.NydusNetwork) }},
        { Units.InfestationPit,              new List<IPrerequisite> { new UnitPrerequisite(Units.Lair) }},
        { Units.Infestor,                    new List<IPrerequisite> { new UnitPrerequisite(Units.InfestationPit) }},
        { Units.SwarmHost,                   new List<IPrerequisite> { new UnitPrerequisite(Units.InfestationPit) }},
        { Units.Spire,                       new List<IPrerequisite> { new UnitPrerequisite(Units.Lair) }},
        { Units.Corruptor,                   new List<IPrerequisite> { new UnitPrerequisite(Units.Spire) }},
        { Units.Mutalisk,                    new List<IPrerequisite> { new UnitPrerequisite(Units.Spire) }},
        { Units.HydraliskDen,                new List<IPrerequisite> { new UnitPrerequisite(Units.Lair) }},
        { Units.Hydralisk,                   new List<IPrerequisite> { new UnitPrerequisite(Units.HydraliskDen) }},
        { Units.LurkerDen,                   new List<IPrerequisite> { new UnitPrerequisite(Units.HydraliskDen) }},
        { Units.Lurker,                      new List<IPrerequisite> { new UnitPrerequisite(Units.LurkerDen) }},
        { Units.Hive,                        new List<IPrerequisite> { new UnitPrerequisite(Units.InfestationPit) }},
        { Units.Viper,                       new List<IPrerequisite> { new UnitPrerequisite(Units.Hive) }},
        { Units.GreaterSpire,                new List<IPrerequisite> { new UnitPrerequisite(Units.Hive) }},
        { Units.BroodLord,                   new List<IPrerequisite> { new UnitPrerequisite(Units.GreaterSpire) }},
        { Units.UltraliskCavern,             new List<IPrerequisite> { new UnitPrerequisite(Units.Hive) }},
        { Units.Ultralisk,                   new List<IPrerequisite> { new UnitPrerequisite(Units.UltraliskCavern) }},
    };

    public static readonly Dictionary<uint, List<IPrerequisite>> UpgradePrerequisites = new Dictionary<uint, List<IPrerequisite>>
    {
        { Upgrades.ZergMissileWeaponsLevel1, new List<IPrerequisite> { new UnitPrerequisite(Units.EvolutionChamber) }},
        { Upgrades.ZergMissileWeaponsLevel2, new List<IPrerequisite> { new TechPrerequisite(Upgrades.ZergMissileWeaponsLevel1), new UnitPrerequisite(Units.Lair) }},
        { Upgrades.ZergMissileWeaponsLevel3, new List<IPrerequisite> { new TechPrerequisite(Upgrades.ZergMissileWeaponsLevel2), new UnitPrerequisite(Units.Hive) }},
        { Upgrades.ZergMeleeWeaponsLevel1,   new List<IPrerequisite> { new UnitPrerequisite(Units.EvolutionChamber) }},
        { Upgrades.ZergMeleeWeaponsLevel2,   new List<IPrerequisite> { new TechPrerequisite(Upgrades.ZergMeleeWeaponsLevel1), new UnitPrerequisite(Units.Lair) }},
        { Upgrades.ZergMeleeWeaponsLevel3,   new List<IPrerequisite> { new TechPrerequisite(Upgrades.ZergMeleeWeaponsLevel2), new UnitPrerequisite(Units.Hive) }},
        { Upgrades.ZergGroundArmorsLevel1,   new List<IPrerequisite> { new UnitPrerequisite(Units.EvolutionChamber) }},
        { Upgrades.ZergGroundArmorsLevel2,   new List<IPrerequisite> { new TechPrerequisite(Upgrades.ZergGroundArmorsLevel1), new UnitPrerequisite(Units.Lair) }},
        { Upgrades.ZergGroundArmorsLevel3,   new List<IPrerequisite> { new TechPrerequisite(Upgrades.ZergGroundArmorsLevel2), new UnitPrerequisite(Units.Hive) }},
        { Upgrades.GlialReconstitution,      new List<IPrerequisite> { new UnitPrerequisite(Units.RoachWarren), new UnitPrerequisite(Units.Lair) }},
        { Upgrades.TunnelingClaws,           new List<IPrerequisite> { new UnitPrerequisite(Units.RoachWarren), new UnitPrerequisite(Units.Lair) }},
        { Upgrades.Burrow,                   new List<IPrerequisite> { new UnitPrerequisite(Units.Hatchery) }},
    };
}
