using System.Collections.Generic;

namespace Bot.GameData;

public static class TechTree {
    public static readonly Dictionary<uint, uint> Producer = new Dictionary<uint, uint>
    {
        { Units.Drone,                       Units.Larva },
        { Units.Corruptor,                   Units.Larva },
        { Units.BroodLord,                   Units.Corruptor },
        { Units.Hydralisk,                   Units.Larva },
        { Units.Lurker,                      Units.Hydralisk },
        { Units.Infestor,                    Units.Larva },
        { Units.Mutalisk,                    Units.Larva },
        { Units.Overlord,                    Units.Larva },
        { Units.Overseer,                    Units.Overlord },
        { Units.Queen,                       Units.Hatchery },
        { Units.Roach,                       Units.Larva },
        { Units.Ravager,                     Units.Roach },
        { Units.Ultralisk,                   Units.Larva },
        { Units.Zergling,                    Units.Larva },
        { Units.SwarmHost,                   Units.Larva },
        { Units.Viper,                       Units.Larva },
        { Units.Baneling,                    Units.Zergling },
        { Units.BanelingNest,                Units.Drone },
        { Units.EvolutionChamber,            Units.Drone },
        { Units.Extractor,                   Units.Drone },
        { Units.Hatchery,                    Units.Drone },
        { Units.Lair,                        Units.Hatchery },
        { Units.Hive,                        Units.Lair },
        { Units.HydraliskDen,                Units.Drone },
        { Units.LurkerDen,                   Units.HydraliskDen },
        { Units.InfestationPit,              Units.Drone },
        { Units.NydusNetwork,                Units.Drone },
        { Units.RoachWarren,                 Units.Drone },
        { Units.SpawningPool,                Units.Drone },
        { Units.SpineCrawler,                Units.Drone },
        { Units.Spire,                       Units.Drone },
        { Units.GreaterSpire,                Units.Spire },
        { Units.SporeCrawler,                Units.Drone },
        { Units.UltraliskCavern,             Units.Drone },

        { Upgrades.ZergMissileWeaponsLevel1, Units.EvolutionChamber },
        { Upgrades.GlialReconstitution,      Units.RoachWarren },
        { Upgrades.TunnelingClaws,           Units.RoachWarren },
        { Upgrades.Burrow,                   Units.Hatchery },
    };

    public static readonly Dictionary<uint, uint> MorphSource = new Dictionary<uint, uint>
    {
        { Units.Drone,            Units.Larva },
        { Units.Corruptor,        Units.Larva },
        { Units.BroodLord,        Units.Corruptor },
        { Units.Hydralisk,        Units.Larva },
        { Units.Lurker,           Units.Hydralisk },
        { Units.Infestor,         Units.Larva },
        { Units.Mutalisk,         Units.Larva },
        { Units.Overlord,         Units.Larva },
        { Units.Overseer,         Units.Overlord },
        { Units.Roach,            Units.Larva },
        { Units.Ravager,          Units.Roach },
        { Units.Ultralisk,        Units.Larva },
        { Units.Zergling,         Units.Larva },
        { Units.SwarmHost,        Units.Larva },
        { Units.Viper,            Units.Larva },
        { Units.Baneling,         Units.Zergling },
        { Units.BanelingNest,     Units.Drone },
        { Units.EvolutionChamber, Units.Drone },
        { Units.Extractor,        Units.Drone },
        { Units.Hatchery,         Units.Drone },
        { Units.Lair,             Units.Hatchery },
        { Units.Hive,             Units.Lair },
        { Units.HydraliskDen,     Units.Drone },
        { Units.LurkerDen,        Units.Drone },
        { Units.InfestationPit,   Units.Drone },
        { Units.NydusNetwork,     Units.Drone },
        { Units.RoachWarren,      Units.Drone },
        { Units.SpawningPool,     Units.Drone },
        { Units.SpineCrawler,     Units.Drone },
        { Units.Spire,            Units.Drone },
        { Units.GreaterSpire,     Units.Spire },
        { Units.SporeCrawler,     Units.Drone },
        { Units.UltraliskCavern,  Units.Drone },
    };

    public static readonly Dictionary<uint, uint> Prerequisite = new Dictionary<uint, uint>
    {
        { Units.EvolutionChamber,            Units.Hatchery },
        { Units.SpawningPool,                Units.Hatchery },
        { Units.Zergling,                    Units.SpawningPool },
        { Units.Queen,                       Units.SpawningPool },
        { Units.SpineCrawler,                Units.SpawningPool },
        { Units.SporeCrawler,                Units.SpawningPool },
        { Units.BanelingNest,                Units.SpawningPool },
        { Units.Baneling,                    Units.BanelingNest },
        { Units.RoachWarren,                 Units.SpawningPool },
        { Units.Roach,                       Units.RoachWarren },
        { Units.Ravager,                     Units.RoachWarren },
        { Units.Lair,                        Units.SpawningPool },
        { Units.Overseer,                    Units.Lair },
        { Units.NydusNetwork,                Units.Lair },
        { Units.NydusWorm,                   Units.NydusNetwork },
        { Units.InfestationPit,              Units.Lair },
        { Units.Infestor,                    Units.InfestationPit },
        { Units.SwarmHost,                   Units.InfestationPit },
        { Units.Spire,                       Units.Lair },
        { Units.Corruptor,                   Units.Spire },
        { Units.Mutalisk,                    Units.Spire },
        { Units.HydraliskDen,                Units.Lair },
        { Units.Hydralisk,                   Units.HydraliskDen },
        { Units.LurkerDen,                   Units.HydraliskDen },
        { Units.Lurker,                      Units.LurkerDen },
        { Units.Hive,                        Units.Lair },
        { Units.Viper,                       Units.Hive },
        { Units.GreaterSpire,                Units.Hive },
        { Units.BroodLord,                   Units.GreaterSpire },
        { Units.UltraliskCavern,             Units.Hive },
        { Units.Ultralisk,                   Units.UltraliskCavern },

        { Upgrades.ZergMissileWeaponsLevel1, Units.EvolutionChamber },
        { Upgrades.GlialReconstitution,      Units.RoachWarren },
        { Upgrades.TunnelingClaws,           Units.RoachWarren },
        { Upgrades.Burrow,                   Units.Hatchery },
    };
}
